# Generated by Django 4.2.5 on 2023-10-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_aluno_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nota',
            field=models.IntegerField(null=True),
        ),
    ]
