# Generated by Django 4.2.5 on 2023-10-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_aluno_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nota',
            field=models.IntegerField(),
        ),
    ]
